### ISSUE TITLE
Small grammer/typo fixes

### ISSUE THREAD

**Issue by Maggers** [Microsoft/Windows-AppConsult-PWALab#9]
Hello,

Aaron shared with me this lab and I spotted a couple of spelling things you could clean up:

under Objectives, you probably should change caching to cache
help you **caching** the incoming
​
Overview of the lab. Bullet point 1:
install and **use it the website** even
​Same bullet point: that **runs in background**

**Comment by qmatteoq** [comment]
Thanks! Fixed in 9d5e6e1b6d37072b101c676e4d057da36275cd36
